name: cloudipsp_mobile
description: Cloudipsp SDK for Mobile(Android, iOS)
version: 0.1.0
author: Maxim Kozenko
homepage: https://github.com/cloudipsp/flutter-mobile-sdk

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: "^2.0.10"
  http: "^0.13.3"
  email_validator: "^1.0.6"

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.cloudipsp.mobile
        pluginClass: CloudipspMobilePlugin
      ios:
        pluginClass: CloudipspMobilePlugin
